[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
address = "127.0.0.1"
port = 8501
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
